//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursoEducativo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tema
    {
        public int IdTema { get; set; }
        public string NombreTema { get; set; }
        public string Periodo { get; set; }
        public string Descripcion { get; set; }
        public string NombreCurso { get; set; }
        public Nullable<int> Curso_IdCurso { get; set; }
    }
}
